### PR TITLE
STOR-1065: Rework sidecar bindings to bind common ClusterRoles

### PR DESCRIPTION
**Pull request by mpatlasov**
PR https://github.com/openshift/cluster-storage-operator/pull/379 published builiding blocks of sidecar ClusterRoles. Now, azure-disk csi driver operator may compose its sidecars ClusterRoles from those building blocks.

This PR also moves permissions for `leases` resource from ClusterRole to per-namespace Role (`assets/rbac/lease_leader_election_role.yaml`).

### CODE REVIEW

**Comment by mpatlasov** [comment]
@ropatil010 , `ci/prow/e2e-azurestack-csi` is optional and it always fail: https://prow.ci.openshift.org/job-history/gs/origin-ci-test/pr-logs/directory/pull-ci-openshift-azure-disk-csi-driver-operator-master-e2e-azurestack-csi. I think we can proceed with this PR despite this test failures. (Lemme know if you think `ci/prow/e2e-azurestack-csi`  is really required here)

**Comment by ropatil010** [comment]
Thanks @mpatlasov for confirmation. 
Bases on the regression testing: PASS and results updated here: [STOR-1363](https://issues.redhat.com/browse/STOR-1363#:~:text=Red%20Hat%20Employee-,Platform%3A%20Azure%3A%C2%A0,-Payload%3A%204.14.0%2D0) 
/label qe-approved

**Pull request merged**
