### PR TITLE
Bug 2038934: Bump(library-go): to get leader election changes

### PR DESCRIPTION
**Pull request by bertinatto**
CC @openshift/storage

### CODE REVIEW

**Comment by jsafrane** [comment]
CI failures look unrelated, but concerning

**Comment by bertinatto** [comment]
/override  ci/prow/e2e-azurestack-csi
There are issues with our AzureStackHub env.

**Comment by jsafrane** [comment]
/override e2e-azurestack-csi
See https://coreos.slack.com/archives/CEKNRGF25/p1643050388075300

**Pull request merged**
