### PR TITLE
Bug 2029570: Add custom CA bundle support

### PR DESCRIPTION
**Pull request by bertinatto**
In OCP, it's possible to set a cluster-wide proxy that operators can use to communicate with external APIs [1]. In addition to that, users can also define a custom CA bundle to be used together with the proxy setting.

Currently, we are not using that custom CA bundle and this patch fixes that. The main benefit of injecting the CA bundle using the CSI controllers, as opposed to statically mount it using the manifest file, is that we can watch for changes in the trusted CA bundle store and roll out a new Deployment with the new CA bundle injected.

[1] https://docs.openshift.com/container-platform/4.10/networking/enable-cluster-wide-proxy.html

CC @openshift/storage

### CODE REVIEW

**Comment by bertinatto** [comment]
/retitle Bug 2029570: Add custom CA bundle support

I discuss this change with the team and we decided to follow this route.

**Comment by patrickdillon** [comment]
When I tested this the csi-driver is crashing with:

```
W0104 18:39:31.538122       1 nodeserver.go:325] get instance type(padillon01041256-zhnxq-master-0) failed with: no credentials provided for Azure cloud provider
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb8 pc=0x159d228]

goroutine 67 [running]:
sigs.k8s.io/cloud-provider-azure/pkg/provider.(*Cloud).GetZone(0xc000312900, {0x2, 0x2})
	/go/src/github.com/openshift/azure-disk-csi-driver/vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_zones.go:179 +0x3a8
sigs.k8s.io/azuredisk-csi-driver/pkg/azuredisk.(*Driver).NodeGetInfo(0xc0002beb40, {0x1c7f6d8, 0xc0003389f0}, 0x20d13d9)
	/go/src/github.com/openshift/azure-disk-csi-driver/pkg/azuredisk/nodeserver.go:336 +0x231
github.com/container-storage-interface/spec/lib/go/csi._Node_NodeGetInfo_Handler.func1({0x1c7f6d8, 0xc0003389f0}, {0x1902e60, 0xc0003bc0a0})
	/go/src/github.com/openshift/azure-disk-csi-driver/vendor/github.com/container-storage-interface/spec/lib/go/csi/csi.pb.go:6236 +0x78
sigs.k8s.io/azuredisk-csi-driver/pkg/csi-common.logGRPC({0x1c7f6d8, 0xc0003389f0}, {0x1902e60, 0xc0003bc0a0}, 0xc0003bc0c0, 0xc00036a198)
	/go/src/github.com/openshift/azure-disk-csi-driver/pkg/csi-common/utils.go:98 +0x514
github.com/container-storage-interface/spec/lib/go/csi._Node_NodeGetInfo_Handler({0x1a1bb60, 0xc0002beb40}, {0x1c7f6d8, 0xc0003389f0}, 0xc000114420, 0x1b0a460)
	/go/src/github.com/openshift/azure-disk-csi-driver/vendor/github.com/container-storage-interface/spec/lib/go/csi/csi.pb.go:6238 +0x138
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000fc780, {0x1cab0f0, 0xc0000e7500}, 0xc00026f800, 0xc000176870, 0x2a2cde8, 0x0)
	/go/src/github.com/openshift/azure-disk-csi-driver/vendor/google.golang.org/grpc/server.go:1024 +0xd1e
google.golang.org/grpc.(*Server).handleStream(0xc0000fc780, {0x1cab0f0, 0xc0000e7500}, 0xc00026f800, 0x0)
	/go/src/github.com/openshift/azure-disk-csi-driver/vendor/google.golang.org/grpc/server.go:1313 +0xa56
google.golang.org/grpc.(*Server).serveStreams.func1.1()
	/go/src/github.com/openshift/azure-disk-csi-driver/vendor/google.golang.org/grpc/server.go:722 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/go/src/github.com/openshift/azure-disk-csi-driver/vendor/google.golang.org/grpc/server.go:720 +0xef
```

Are you using the credentials created from the credential request?

**Comment by bertinatto** [comment]
> When I tested this the csi-driver is crashing with:
> 
> ```
> W0104 18:39:31.538122       1 nodeserver.go:325] get instance type(padillon01041256-zhnxq-master-0) failed with: no credentials provided for Azure cloud provider
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0xb8 pc=0x159d228]
> 
> goroutine 67 [running]:
> sigs.k8s.io/cloud-provider-azure/pkg/provider.(*Cloud).GetZone(0xc000312900, {0x2, 0x2})
> 	/go/src/github.com/openshift/azure-disk-csi-driver/vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_zones.go:179 +0x3a8
> sigs.k8s.io/azuredisk-csi-driver/pkg/azuredisk.(*Driver).NodeGetInfo(0xc0002beb40, {0x1c7f6d8, 0xc0003389f0}, 0x20d13d9)
> 	/go/src/github.com/openshift/azure-disk-csi-driver/pkg/azuredisk/nodeserver.go:336 +0x231
> github.com/container-storage-interface/spec/lib/go/csi._Node_NodeGetInfo_Handler.func1({0x1c7f6d8, 0xc0003389f0}, {0x1902e60, 0xc0003bc0a0})
> 	/go/src/github.com/openshift/azure-disk-csi-driver/vendor/github.com/container-storage-interface/spec/lib/go/csi/csi.pb.go:6236 +0x78
> sigs.k8s.io/azuredisk-csi-driver/pkg/csi-common.logGRPC({0x1c7f6d8, 0xc0003389f0}, {0x1902e60, 0xc0003bc0a0}, 0xc0003bc0c0, 0xc00036a198)
> 	/go/src/github.com/openshift/azure-disk-csi-driver/pkg/csi-common/utils.go:98 +0x514
> github.com/container-storage-interface/spec/lib/go/csi._Node_NodeGetInfo_Handler({0x1a1bb60, 0xc0002beb40}, {0x1c7f6d8, 0xc0003389f0}, 0xc000114420, 0x1b0a460)
> 	/go/src/github.com/openshift/azure-disk-csi-driver/vendor/github.com/container-storage-interface/spec/lib/go/csi/csi.pb.go:6238 +0x138
> google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000fc780, {0x1cab0f0, 0xc0000e7500}, 0xc00026f800, 0xc000176870, 0x2a2cde8, 0x0)
> 	/go/src/github.com/openshift/azure-disk-csi-driver/vendor/google.golang.org/grpc/server.go:1024 +0xd1e
> google.golang.org/grpc.(*Server).handleStream(0xc0000fc780, {0x1cab0f0, 0xc0000e7500}, 0xc00026f800, 0x0)
> 	/go/src/github.com/openshift/azure-disk-csi-driver/vendor/google.golang.org/grpc/server.go:1313 +0xa56
> google.golang.org/grpc.(*Server).serveStreams.func1.1()
> 	/go/src/github.com/openshift/azure-disk-csi-driver/vendor/google.golang.org/grpc/server.go:722 +0x98
> created by google.golang.org/grpc.(*Server).serveStreams.func1
> 	/go/src/github.com/openshift/azure-disk-csi-driver/vendor/google.golang.org/grpc/server.go:720 +0xef
> ```
> 
> Are you using the credentials created from the credential request?

@patrickdillon: yes, the [credentials used by the CSI Driver](https://github.com/openshift/azure-disk-csi-driver-operator/blob/master/assets/controller.yaml#L55) are provided by CCO. CVO is supposed to apply the [CredentialsRequest specified here](https://github.com/openshift/cluster-storage-operator/blob/master/manifests/03_credentials_request_azure.yaml).

Is there anything special in this environment that prevents those credentials to be created?

**Comment by patrickdillon** [comment]
@bertinatto Sorry, I should have posted the complete logs. It looks like the cause of failure is probably happening earlier. Here are the complete logs:

```
Streaming logs below:
I0104 18:39:29.642000       1 azuredisk.go:145] driver userAgent: disk.csi.azure.com/v1.9.0 gc/go1.17.2 (amd64-linux)
I0104 18:39:29.642883       1 azure_disk_utils.go:129] reading cloud config from secret kube-system/azure-cloud-provider
W0104 18:39:29.654710       1 azure_disk_utils.go:136] InitializeCloudFromSecret: failed to get cloud config from secret kube-system/azure-cloud-provider: failed to get secret kube-system/azure-cloud-provider: secrets "azure-cloud-provider" is forbidden: User "system:serviceaccount:openshift-cluster-csi-drivers:azure-disk-csi-driver-node-sa" cannot get resource "secrets" in API group "" in the namespace "kube-system"
I0104 18:39:29.654728       1 azure_disk_utils.go:141] could not read cloud config from secret kube-system/azure-cloud-provider
I0104 18:39:29.654734       1 azure_disk_utils.go:144] AZURE_CREDENTIAL_FILE env var set as /etc/kubernetes/cloud.conf
I0104 18:39:29.654751       1 azure_disk_utils.go:159] read cloud config from file: /etc/kubernetes/cloud.conf successfully
W0104 18:39:29.673029       1 azure_disk_utils.go:182] InitializeCloudFromConfig failed with error: Get "https://management.mtcazs.wwtatc.com/metadata/endpoints?api-version=1.0": x509: certificate signed by unknown authority
I0104 18:39:29.679435       1 mount_linux.go:202] Cannot run systemd-run, assuming non-systemd OS
I0104 18:39:29.679453       1 driver.go:81] Enabling controller service capability: CREATE_DELETE_VOLUME
I0104 18:39:29.679458       1 driver.go:81] Enabling controller service capability: PUBLISH_UNPUBLISH_VOLUME
I0104 18:39:29.679463       1 driver.go:81] Enabling controller service capability: CREATE_DELETE_SNAPSHOT
I0104 18:39:29.679466       1 driver.go:81] Enabling controller service capability: LIST_SNAPSHOTS
I0104 18:39:29.679469       1 driver.go:81] Enabling controller service capability: CLONE_VOLUME
I0104 18:39:29.679472       1 driver.go:81] Enabling controller service capability: EXPAND_VOLUME
I0104 18:39:29.679475       1 driver.go:81] Enabling controller service capability: LIST_VOLUMES
I0104 18:39:29.679478       1 driver.go:81] Enabling controller service capability: LIST_VOLUMES_PUBLISHED_NODES
I0104 18:39:29.679480       1 driver.go:81] Enabling controller service capability: SINGLE_NODE_MULTI_WRITER
I0104 18:39:29.679484       1 driver.go:100] Enabling volume access mode: SINGLE_NODE_WRITER
I0104 18:39:29.679487       1 driver.go:100] Enabling volume access mode: SINGLE_NODE_READER_ONLY
I0104 18:39:29.679489       1 driver.go:100] Enabling volume access mode: SINGLE_NODE_SINGLE_WRITER
I0104 18:39:29.679492       1 driver.go:100] Enabling volume access mode: SINGLE_NODE_MULTI_WRITER
I0104 18:39:29.679501       1 driver.go:91] Enabling node service capability: STAGE_UNSTAGE_VOLUME
I0104 18:39:29.679505       1 driver.go:91] Enabling node service capability: EXPAND_VOLUME
I0104 18:39:29.679508       1 driver.go:91] Enabling node service capability: GET_VOLUME_STATS
I0104 18:39:29.679511       1 driver.go:91] Enabling node service capability: SINGLE_NODE_MULTI_WRITER
I0104 18:39:29.679624       1 server.go:117] Listening for connections on address: &net.UnixAddr{Name:"//csi/csi.sock", Net:"unix"}
I0104 18:39:29.794750       1 utils.go:95] GRPC call: /csi.v1.Identity/GetPluginInfo
I0104 18:39:29.794775       1 utils.go:96] GRPC request: {}
I0104 18:39:29.796347       1 utils.go:102] GRPC response: {"name":"disk.csi.azure.com","vendor_version":"v1.9.0"}
I0104 18:39:31.538056       1 utils.go:95] GRPC call: /csi.v1.Node/NodeGetInfo
I0104 18:39:31.538075       1 utils.go:96] GRPC request: {}
W0104 18:39:31.538122       1 nodeserver.go:325] get instance type(padillon01041256-zhnxq-master-0) failed with: no credentials provided for Azure cloud provider
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb8 pc=0x159d228]

goroutine 67 [running]:
sigs.k8s.io/cloud-provider-azure/pkg/provider.(*Cloud).GetZone(0xc000312900, {0x2, 0x2})
	/go/src/github.com/openshift/azure-disk-csi-driver/vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_zones.go:179 +0x3a8
sigs.k8s.io/azuredisk-csi-driver/pkg/azuredisk.(*Driver).NodeGetInfo(0xc0002beb40, {0x1c7f6d8, 0xc0003389f0}, 0x20d13d9)
	/go/src/github.com/openshift/azure-disk-csi-driver/pkg/azuredisk/nodeserver.go:336 +0x231
github.com/container-storage-interface/spec/lib/go/csi._Node_NodeGetInfo_Handler.func1({0x1c7f6d8, 0xc0003389f0}, {0x1902e60, 0xc0003bc0a0})
	/go/src/github.com/openshift/azure-disk-csi-driver/vendor/github.com/container-storage-interface/spec/lib/go/csi/csi.pb.go:6236 +0x78
sigs.k8s.io/azuredisk-csi-driver/pkg/csi-common.logGRPC({0x1c7f6d8, 0xc0003389f0}, {0x1902e60, 0xc0003bc0a0}, 0xc0003bc0c0, 0xc00036a198)
	/go/src/github.com/openshift/azure-disk-csi-driver/pkg/csi-common/utils.go:98 +0x514
github.com/container-storage-interface/spec/lib/go/csi._Node_NodeGetInfo_Handler({0x1a1bb60, 0xc0002beb40}, {0x1c7f6d8, 0xc0003389f0}, 0xc000114420, 0x1b0a460)
	/go/src/github.com/openshift/azure-disk-csi-driver/vendor/github.com/container-storage-interface/spec/lib/go/csi/csi.pb.go:6238 +0x138
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000fc780, {0x1cab0f0, 0xc0000e7500}, 0xc00026f800, 0xc000176870, 0x2a2cde8, 0x0)
	/go/src/github.com/openshift/azure-disk-csi-driver/vendor/google.golang.org/grpc/server.go:1024 +0xd1e
google.golang.org/grpc.(*Server).handleStream(0xc0000fc780, {0x1cab0f0, 0xc0000e7500}, 0xc00026f800, 0x0)
	/go/src/github.com/openshift/azure-disk-csi-driver/vendor/google.golang.org/grpc/server.go:1313 +0xa56
google.golang.org/grpc.(*Server).serveStreams.func1.1()
	/go/src/github.com/openshift/azure-disk-csi-driver/vendor/google.golang.org/grpc/server.go:722 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/go/src/github.com/openshift/azure-disk-csi-driver/vendor/google.golang.org/grpc/server.go:720 +0xef

```

**Comment by patrickdillon** [comment]
`
W0104 18:39:29.673029       1 azure_disk_utils.go:182] InitializeCloudFromConfig failed with error: Get "https://management.mtcazs.wwtatc.com/metadata/endpoints?api-version=1.0": x509: certificate signed by unknown authority
`

**Comment by bertinatto** [comment]
@patrickdillon thank you for the logs. It seems like I forgot to add some [required changes](https://github.com/openshift/azure-disk-csi-driver-operator/pull/38/commits/912d5353bad966d6c746c5a9d518981ec9ba02cf#diff-529b166853e98d1126b70e972faa93f1355cb4283af58abf08d9d96509d00cbdR8) to my PR. Could you please try again?

**Comment by patrickdillon** [comment]
Looks good:
```
Streaming logs below:
I0104 21:12:02.329301       1 azuredisk.go:145] driver userAgent: disk.csi.azure.com/v1.9.0 gc/go1.17.2 (amd64-linux)
I0104 21:12:02.330177       1 azure_disk_utils.go:129] reading cloud config from secret kube-system/azure-cloud-provider
W0104 21:12:02.336722       1 azure_disk_utils.go:136] InitializeCloudFromSecret: failed to get cloud config from secret kube-system/azure-cloud-provider: failed to get secret kube-system/azure-cloud-provider: secrets "azure-cloud-provider" is forbidden: User "system:serviceaccount:openshift-cluster-csi-drivers:azure-disk-csi-driver-node-sa" cannot get resource "secrets" in API group "" in the namespace "kube-system"
I0104 21:12:02.336741       1 azure_disk_utils.go:141] could not read cloud config from secret kube-system/azure-cloud-provider
I0104 21:12:02.336748       1 azure_disk_utils.go:144] AZURE_CREDENTIAL_FILE env var set as /etc/kubernetes/cloud.conf
I0104 21:12:02.336767       1 azure_disk_utils.go:159] read cloud config from file: /etc/kubernetes/cloud.conf successfully
I0104 21:12:02.365193       1 azure_auth.go:119] azure: using client_id+client_secret to retrieve access token
I0104 21:12:02.365224       1 azure.go:692] Azure cloudprovider using try backoff: retries=6, exponent=1.500000, duration=6, jitter=1.000000
I0104 21:12:02.365276       1 azure_diskclient.go:67] Azure DisksClient using API version: 2019-03-01
I0104 21:12:02.365334       1 azure.go:909] attach/detach disk operation rate limit QPS: 6.000000, Bucket: 10
I0104 21:12:02.372458       1 mount_linux.go:202] Cannot run systemd-run, assuming non-systemd OS
I0104 21:12:02.372474       1 driver.go:81] Enabling controller service capability: CREATE_DELETE_VOLUME
I0104 21:12:02.372480       1 driver.go:81] Enabling controller service capability: PUBLISH_UNPUBLISH_VOLUME
I0104 21:12:02.372484       1 driver.go:81] Enabling controller service capability: CREATE_DELETE_SNAPSHOT
I0104 21:12:02.372488       1 driver.go:81] Enabling controller service capability: LIST_SNAPSHOTS
I0104 21:12:02.372491       1 driver.go:81] Enabling controller service capability: CLONE_VOLUME
I0104 21:12:02.372495       1 driver.go:81] Enabling controller service capability: EXPAND_VOLUME
I0104 21:12:02.372499       1 driver.go:81] Enabling controller service capability: LIST_VOLUMES
I0104 21:12:02.372502       1 driver.go:81] Enabling controller service capability: LIST_VOLUMES_PUBLISHED_NODES
I0104 21:12:02.372507       1 driver.go:81] Enabling controller service capability: SINGLE_NODE_MULTI_WRITER
I0104 21:12:02.372513       1 driver.go:100] Enabling volume access mode: SINGLE_NODE_WRITER
I0104 21:12:02.372518       1 driver.go:100] Enabling volume access mode: SINGLE_NODE_READER_ONLY
I0104 21:12:02.372521       1 driver.go:100] Enabling volume access mode: SINGLE_NODE_SINGLE_WRITER
I0104 21:12:02.372526       1 driver.go:100] Enabling volume access mode: SINGLE_NODE_MULTI_WRITER
I0104 21:12:02.372531       1 driver.go:91] Enabling node service capability: STAGE_UNSTAGE_VOLUME
I0104 21:12:02.372536       1 driver.go:91] Enabling node service capability: EXPAND_VOLUME
I0104 21:12:02.372541       1 driver.go:91] Enabling node service capability: GET_VOLUME_STATS
I0104 21:12:02.372546       1 driver.go:91] Enabling node service capability: SINGLE_NODE_MULTI_WRITER
I0104 21:12:02.372813       1 server.go:117] Listening for connections on address: &net.UnixAddr{Name:"//csi/csi.sock", Net:"unix"}
I0104 21:12:04.703333       1 utils.go:95] GRPC call: /csi.v1.Identity/GetPluginInfo
I0104 21:12:04.703351       1 utils.go:96] GRPC request: {}
I0104 21:12:04.704373       1 utils.go:102] GRPC response: {"name":"disk.csi.azure.com","vendor_version":"v1.9.0"}
I0104 21:12:04.716384       1 utils.go:95] GRPC call: /csi.v1.Node/NodeGetInfo
I0104 21:12:04.716467       1 utils.go:96] GRPC request: {}
I0104 21:12:05.290583       1 utils.go:102] GRPC response: {"accessible_topology":{"segments":{"topology.disk.csi.azure.com/zone":""}},"max_volumes_per_node":32,"node_id":"padillon01041555-ptjrj-master-0"}
I0104 21:12:06.898183       1 utils.go:95] GRPC call: /csi.v1.Identity/GetPluginInfo
I0104 21:12:06.898203       1 utils.go:96] GRPC request: {}
I0104 21:12:06.898244       1 utils.go:102] GRPC response: {"name":"disk.csi.azure.com","vendor_version":"v1.9.0"}
```

Unfortunately https://bugzilla.redhat.com/show_bug.cgi?id=2034413 is blocking bootstrap complete so the storage operator is still progressing. Anything else you suggest I check?

If we could get a 4.9 cherry-pick for this then we should be able to get to cluster complete. The BZ above is only introduced in 4.10. (We will need this cherry-picked to 4.9 regardless.)

**Comment by bertinatto** [comment]
> @bertinatto Any thoughts on the 4.9 backport? There is a PR + workaround for the 4.10 blocker BZ, so I might try another round of testing for this.

@patrickdillon sure, we'll definitely backport to 4.9 once this is merged.

**Comment by jsafrane** [comment]
lgtm

**Comment by bertinatto** [comment]
/override ci/prow/e2e-azurestack-csi 

https://bugzilla.redhat.com/show_bug.cgi?id=2034460

**Pull request merged**
