### PR TITLE
CCO-324: Unrevert "CCO-324: add support for workload identity"

### PR DESCRIPTION
**Pull request by bertinatto**
CC @openshift/storage

### CODE REVIEW

**Comment by bertinatto** [comment]
/hold
until this is properly tested

**Comment by bertinatto** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.14-e2e-azure-sdn-techpreview

**Comment by bertinatto** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.14-e2e-azure-sdn-techpreview

**Comment by bertinatto** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.14-e2e-azure-sdn-techpreview

**Comment by bertinatto** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.14-e2e-azure-sdn-techpreview

**Comment by duanwei33** [comment]
See pre-merge test result in https://issues.redhat.com/browse/STOR-1319.

**Comment by duanwei33** [comment]
Also enabling TechPreviewNoUpgrade will not break the storage CO with the PR.

**Pull request merged**
