### PR TITLE
STOR-947: support disabling default StorageClass via ClusterCSIDriver

### PR DESCRIPTION
**Pull request by dobsonj**
https://issues.redhat.com/browse/STOR-947
Marking this WIP until openshift/library-go#1441 merges.
/cc @openshift/storage

### CODE REVIEW

**Comment by ropatil010** [comment]
Payload: 4.13.0-0.ci.test-2023-01-25-044031-ci-ln-8y8dp9t-latest

Test Results: 
###################test0_Default started #################
oc get clustercsidriver disk.csi.azure.com -o yaml | grep 'storageClassState'

oc get sc
NAME                    PROVISIONER          RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
azurefile-csi                   file.csi.azure.com     Delete            Immediate                      true                   36s
managed-csi (default)   disk.csi.azure.com   Delete          WaitForFirstConsumer   true                   30s

 change managed-csi volumeBindingMode
 change managed-csi reclaimPolicy
 change azurefile-csi volumeBindingMode
 change azurefile-csi reclaimPolicy

 Bydefault test change managed-csi allowVolumeExpansion to false
storageclass.storage.k8s.io/managed-csi patched
 Bydefault result oc get sc managed-csi
NAME                    PROVISIONER          RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
managed-csi (default)   disk.csi.azure.com   Delete          WaitForFirstConsumer   true                   64s

 Bydefault test change azurefile-csi allowVolumeExpansion to false
storageclass.storage.k8s.io/azurefile-csi patched
 Bydefault result oc get sc azurefile-csi
NAME            PROVISIONER          RECLAIMPOLICY   VOLUMEBINDINGMODE   ALLOWVOLUMEEXPANSION   AGE
azurefile-csi   file.csi.azure.com   Delete          Immediate           true                   82s

oc get sc
NAME                    PROVISIONER          RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
azurefile-csi                    file.csi.azure.com   Delete            Immediate                      true                   88s
managed-csi (default)   disk.csi.azure.com   Delete          WaitForFirstConsumer   true                   82s

oc delete sc azurefile-csi
storageclass.storage.k8s.io "azurefile-csi" deleted
storageclass.storage.k8s.io "managed-csi" deleted

oc get sc
NAME                    PROVISIONER          RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
azurefile-csi           file.csi.azure.com   Delete          Immediate              true                   13s
managed-csi (default)   disk.csi.azure.com   Delete          WaitForFirstConsumer   true                   6s
###################test1_Removed started #################
oc get clustercsidriver disk.csi.azure.com -o yaml | grep 'storageClassState' 
  storageClassState: Removed

 Removed test change managed-csi allowVolumeExpansion to false

 Removed test change azurefile-csi allowVolumeExpansion to false
storageclass.storage.k8s.io/azurefile-csi patched

 Removed result oc get sc
NAME            PROVISIONER          RECLAIMPOLICY   VOLUMEBINDINGMODE   ALLOWVOLUMEEXPANSION   AGE
azurefile-csi   file.csi.azure.com   Delete          Immediate           true                   7m9s
###################test2_Managed started #################
oc get clustercsidriver disk.csi.azure.com -o yaml | grep 'storageClassState'
  storageClassState: Managed

oc get sc
NAME                    PROVISIONER          RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
azurefile-csi                    file.csi.azure.com    Delete           Immediate                       true                   54s
managed-csi (default)   disk.csi.azure.com   Delete          WaitForFirstConsumer   true                   47s

 change managed-csi volumeBindingMode
 change managed-csi reclaimPolicy
 change azurefile-csi volumeBindingMode
 change azurefile-csi reclaimPolicy

 Managed test change managed-csi allowVolumeExpansion to false
storageclass.storage.k8s.io/managed-csi patched
 Managed result oc get sc managed-csi
NAME                    PROVISIONER          RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
managed-csi (default)   disk.csi.azure.com   Delete          WaitForFirstConsumer   true                   81s

 Managed test change azurefile-csi allowVolumeExpansion to false
storageclass.storage.k8s.io/azurefile-csi patched
 Managed result oc get sc azurefile-csi
NAME            PROVISIONER          RECLAIMPOLICY   VOLUMEBINDINGMODE   ALLOWVOLUMEEXPANSION   AGE
azurefile-csi   file.csi.azure.com   Delete          Immediate           true                   101s

oc get sc
NAME                    PROVISIONER          RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
azurefile-csi                   file.csi.azure.com     Delete           Immediate                       true                   107s
managed-csi (default)   disk.csi.azure.com   Delete          WaitForFirstConsumer   true                   100s

oc delete sc azurefile-csi
storageclass.storage.k8s.io "azurefile-csi" deleted
storageclass.storage.k8s.io "managed-csi" deleted

oc get sc
NAME                    PROVISIONER          RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
azurefile-csi                    file.csi.azure.com     Delete          Immediate                       true                   8s
managed-csi (default)   disk.csi.azure.com   Delete          WaitForFirstConsumer   true                   2s
###################test3_Unmanaged started #################
oc get clustercsidriver disk.csi.azure.com -o yaml | grep 'storageClassState'
  storageClassState: Unmanaged

oc get sc
NAME                    PROVISIONER          RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
azurefile-csi                    file.csi.azure.com    Delete           Immediate                       true                   2m9s
managed-csi (default)   disk.csi.azure.com   Delete          WaitForFirstConsumer   true                   2m3s

 change managed-csi volumeBindingMode
 change managed-csi reclaimPolicy
 change azurefile-csi volumeBindingMode
 change azurefile-csi reclaimPolicy

 Unmanaged test change managed-csi allowVolumeExpansion to false
storageclass.storage.k8s.io/managed-csi patched

 Unmanaged result oc get sc managed-csi
NAME                    PROVISIONER          RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
managed-csi (default)   disk.csi.azure.com   Delete          WaitForFirstConsumer   false                  2m42s

 Unmanaged test change azurefile-csi allowVolumeExpansion to false
storageclass.storage.k8s.io/azurefile-csi patched

 Unmanaged result oc get sc azurefile-csi
NAME            PROVISIONER          RECLAIMPOLICY   VOLUMEBINDINGMODE   ALLOWVOLUMEEXPANSION   AGE
azurefile-csi   file.csi.azure.com   Delete          Immediate           true                   2m55s

oc get sc
NAME                    PROVISIONER          RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
azurefile-csi                    file.csi.azure.com    Delete           Immediate                       true                   3m2s
managed-csi (default)   disk.csi.azure.com   Delete          WaitForFirstConsumer   false                  2m56s

oc delete sc azurefile-csi
storageclass.storage.k8s.io "azurefile-csi" deleted
storageclass.storage.k8s.io "managed-csi" deleted

oc get sc
NAME            PROVISIONER          RECLAIMPOLICY   VOLUMEBINDINGMODE   ALLOWVOLUMEEXPANSION   AGE
azurefile-csi   file.csi.azure.com   Delete          Immediate           true                   14s
###################test4a_Multiple default sc started #################
oc get clustercsidriver disk.csi.azure.com -o yaml | grep 'storageClassState'
  storageClassState: Managed

oc get sc
NAME                    PROVISIONER          RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
azurefile-csi                    file.csi.azure.com    Delete          Immediate                        true                   4m30s
managed-csi (default)   disk.csi.azure.com   Delete          WaitForFirstConsumer   true                   68s
Creating sc
storageclass.storage.k8s.io/testsc created
Applying patch to sc testsc for changing to default
storageclass.storage.k8s.io/testsc patched

oc get sc
NAME                    PROVISIONER          RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
azurefile-csi                   file.csi.azure.com      Delete          Immediate                       true                   4m49s
managed-csi (default)   disk.csi.azure.com   Delete          WaitForFirstConsumer   true                   87s
testsc (default)              disk.csi.azure.com    Delete          WaitForFirstConsumer   true                   13s
###################test4b_Removed started #################
oc get clustercsidriver disk.csi.azure.com -o yaml | grep 'storageClassState'
  storageClassState: Removed

oc get sc and check azurefile-csi, managed-csi should not be there, testsc should be there
NAME               PROVISIONER          RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
azurefile-csi        file.csi.azure.com    Delete          Immediate                        true                   8m11s
testsc (default)   disk.csi.azure.com   Delete          WaitForFirstConsumer   true                   3m35s
###################test4c_Managed sc started #################
oc get clustercsidriver disk.csi.azure.com -o yaml | grep 'storageClassState'
  storageClassState: Managed

oc get sc all should be present now azurefile-csi, managed-csi, testsc
NAME               PROVISIONER          RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
azurefile-csi         file.csi.azure.com     Delete          Immediate                       true                   11m
managed-csi        disk.csi.azure.com   Delete          WaitForFirstConsumer   true                   24s
testsc (default)    disk.csi.azure.com   Delete          WaitForFirstConsumer   true                   6m39s
Deleting all sc
storageclass.storage.k8s.io "testsc" deleted
storageclass.storage.k8s.io "azurefile-csi" deleted
storageclass.storage.k8s.io "managed-csi" deleted

oc get sc azurefile-csi and managed-csi should be back to default
NAME                    PROVISIONER          RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
azurefile-csi                    file.csi.azure.com    Delete           Immediate                      true                   9s
managed-csi (default)   disk.csi.azure.com   Delete          WaitForFirstConsumer   true                   7s
###################test5a_Managed default sc started #################
oc get clustercsidriver disk.csi.azure.com -o yaml | grep 'storageClassState'
  storageClassState: Managed

oc get sc
NAME                    PROVISIONER          RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
azurefile-csi                    file.csi.azure.com     Delete          Immediate                      true                   2m12s
managed-csi (default)   disk.csi.azure.com   Delete          WaitForFirstConsumer   true                   2m10s
###################test5b_Unmanaged default sc started #################
oc get clustercsidriver disk.csi.azure.com -o yaml | grep 'storageClassState'
  storageClassState: Unmanaged

oc get sc
NAME                    PROVISIONER          RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
azurefile-csi                    file.csi.azure.com   Delete            Immediate                       true                   3m39s
managed-csi (default)   disk.csi.azure.com   Delete          WaitForFirstConsumer   true                   3m37s
Creating sc
storageclass.storage.k8s.io/testsc created
Applying patch to sc testsc for changing to default
storageclass.storage.k8s.io/testsc patched
Applying patch to sc managed-csi for changing to non default
storageclass.storage.k8s.io/managed-csi patched

oc get sc
NAME               PROVISIONER          RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
azurefile-csi         file.csi.azure.com   Delete          Immediate                         true                   4m
managed-csi        disk.csi.azure.com   Delete          WaitForFirstConsumer   true                   3m58s
testsc (default)    disk.csi.azure.com   Delete          WaitForFirstConsumer   true                   15s
###################test5c_Removed sc started #################
oc get clustercsidriver disk.csi.azure.com -o yaml | grep 'storageClassState'
  storageClassState: Removed

oc get sc managed-csi should not be there, azurefile-csi, testsc should be there
NAME               PROVISIONER          RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
azurefile-csi      file.csi.azure.com   Delete          Immediate              true                   5m50s
testsc (default)   disk.csi.azure.com   Delete          WaitForFirstConsumer   true                   2m5s
Deleting sc testsc
storageclass.storage.k8s.io "testsc" deleted

azurefile-csi should remain
NAME            PROVISIONER          RECLAIMPOLICY   VOLUMEBINDINGMODE   ALLOWVOLUMEEXPANSION   AGE
azurefile-csi   file.csi.azure.com   Delete          Immediate           true                   6m3s

**Comment by dobsonj** [comment]
> /docs-approved

/label docs-approved

**Pull request merged**
